// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9gAatuzt7rU4ZVzJWBNAmelpLtRyTrVk',
    appId: '1:1000828796444:android:97afdb9c9089802e2de9d9',
    messagingSenderId: '1000828796444',
    projectId: 'warunk-eb80b',
    storageBucket: 'warunk-eb80b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrbs_8lYo9ealVepJ7qCV3tn6nrZVRN_8',
    appId: '1:1000828796444:ios:b8dd6cb8bcf62c6f2de9d9',
    messagingSenderId: '1000828796444',
    projectId: 'warunk-eb80b',
    storageBucket: 'warunk-eb80b.firebasestorage.app',
    androidClientId: '1000828796444-bpkv5fqd0mlfpk3nnnbubgt239i0pc04.apps.googleusercontent.com',
    iosClientId: '1000828796444-uj9b2k2sks8ml1aqnhicrnekvmilbka7.apps.googleusercontent.com',
    iosBundleId: 'com.watuka.warunk',
  );

}